version: "3.4"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: shareit
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - "5432:5432"